# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('dualsocketapp', ['core','internet','wifi','lte', 'nr'])
    module.source = [
        'model/udp-dualsocket-client.cc',
        'model/udp-dualsocket-server.cc',
        'model/unique-packet-id-tag.cc',
        'helper/udp-dualsocket-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('dualsocketapp')
    module_test.source = [
        'test/dualsocketapp-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'dualsocketapp'
    headers.source = [
        'model/udp-dualsocket-client.h',
        'model/udp-dualsocket-server.h',
        'model/unique-packet-id-tag.h',
        'helper/udp-dualsocket-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
